### ISSUE TITLE
Missing release / license / dependency to psalm

### ISSUE THREAD

**Issue by ckrack** [BafS/psalm-typecov#1]
Hi Fabien, nice looking package!
I'd like to try this out, but it's missing a few things:
- an initial release
- a reasonable dependency to a psalm version (it currently requires `"vimeo/psalm": "dev-master"`)
- a License

It would be great if you can pick this up after the two years that passed since your last commit.
Of course I understand that everyone in our area is busy and that you might have moved on to other things.

Regards, Clemens

**Comment by BafS** [comment]
Hello,

Thank you!
I added an explicit file for the license (it was set in composer.json already). I updated psalm dependency and I just did an initial release.

I'll close this issue but let me know if you have any other issue.

Cheers
